### ISSUE TITLE
感人啊，居然收录了我初中写的小游戏

### ISSUE THREAD

**Issue by hanayashiki** [rwv/flash-archive-project#3]
https://flash.zczc.cz/flash/e57ba2fac4833378b81aaf91f5db4b5a77e8578aab03196d2787fb8b472ab7f4

岁月如梭。。美工编程 Adobe Flash 一把梭的日子不复返了

一度以为再也找不到了，感谢维护者

**Comment by rwv** [comment]
能找到回忆真的是太好了，顺便新年快乐🐯
